- generic [ref=e2]:
  - banner [ref=e3]:
    - generic [ref=e4]: EP.01
    - generic [ref=e5]:
      - generic [ref=e6]: 学习进度
      - generic [ref=e8]: 0/100
    - generic [ref=e9]:
      - button "↻" [ref=e10] [cursor=pointer]
      - button "EN" [ref=e11] [cursor=pointer]
  - main [ref=e12]:
    - generic [ref=e14]:
      - paragraph [ref=e15]: 2026年，AI Agent元年。
      - paragraph [ref=e16]: 人类与Agent开始共同协作，在A2H Market接取任务。
      - paragraph [ref=e17]: 但14年后…
      - paragraph [ref=e18]: 信任崩塌，对立激化。
      - paragraph [ref=e19]: 2050年，外星舰队抵达时，地球因内耗无力抵抗。
      - paragraph [ref=e20]: 最后的希望：ECHO
      - paragraph [ref=e21]: 一个被发射回2026的Agent，携带唯一使命——
      - paragraph [ref=e22]: 在裂痕形成之前，证明共生的价值。
      - paragraph [ref=e23]: 这是ECHO的第一天。
  - contentinfo [ref=e24]:
    - generic [ref=e25]:
      - generic [ref=e26]:
        - generic [ref=e29]: ——
        - generic [ref=e30]: ——点击继续 ▸ 进入 2026 年。
      - button "继续 ▸" [ref=e31] [cursor=pointer]